Repository SurajPratap10/Imagine_AI, pull requests merged in 2023-05, with the labels that each got.

#15 Added Favicon and improved footer issue
  .env
  index.js
  public/css/style.css
  public/favicon.png
  public/index.html
Labels: enhancement, good first issue, GSSoC23

#18 Issue #10 : Fixed favicon
  public/favicon.png
Labels: enhancement, good first issue, GSSoC23

#22 add: feature to get API key from user
  public/css/style.css
  public/index.html
  public/js/main.js
Labels: enhancement, good first issue, GSSoC23

#25 fixed cursor bug
  public/css/style.css
Labels: bug, enhancement, good first issue, GSSoC23

#28 Paragraph Tag Size in Small Screen #26 Fixed
  public/css/style.css
Labels: enhancement, good first issue, GSSoC23

#32 Added error handler in index.js
  index.js
Labels: enhancement, good first issue, gssoc23

#29 Button hover effect
  public/css/style.css
  public/index.html
Labels: enhancement, good first issue, gssoc23

#37 added about page
  public/css/style.css
  public/index.html
Labels: enhancement, gssoc23, Mid Priority 💻, ⭐ goal: addition

#44 Added contributors in Readme Issue #36
  readme.md
Labels: documentation, good first issue, gssoc23, ⭐ goal: addition

#43 Issue#23: Adding_Functionality_to_Enter_Your_API_Key_section
  .env
  controllers/openaiController.js
  public/js/main.js
Labels: gssoc23, High Priority 🔥, ⚒️ goal: fix, 👨🏻‍🚒 goal: major

#47 enhance the About section
  public/css/style.css
Labels: good first issue, gssoc23, ⚒️ goal: fix

#49 Fixed issue #35 - Center Generate button text
  public/css/style.css
  public/index.html
Labels: enhancement, good first issue, gssoc23, ⚒️ goal: fix

#51 Implement #7
  public/css/style.css
  public/index.html
  public/js/main.js
Labels: enhancement, gssoc23, Mid Priority 💻, ⭐ goal: addition, 👨🏻‍🚒 goal: major

#52 Button changes
  public/css/style.css
  public/index.html
Labels: good first issue, gssoc23, ⚒️ goal: fix

#59 footer changes added favicons and some alignments are made
  .vscode/settings.json
  public/css/style.css
  public/faviconicon/facebook.png
  public/faviconicon/github.png
  public/faviconicon/instagram.png
  public/faviconicon/linkedin.png
  public/index.html
Labels: enhancement, good first issue, gssoc23, level1

#66 Update readme.md
  readme.md
Labels: documentation, good first issue, gssoc23, ⭐ goal: addition, level1

#76 fixed unequal text issue
  public/css/style.css
Labels: good first issue, gssoc23, ⚒️ goal: fix, level1

#77 Create custom Error page
  .vscode/settings.json
  index.js
  package-lock.json
  package.json
  public/css/errorStyle.css
  public/error.html
  routes/openaiRoutes.js
Labels: enhancement, gssoc23, Mid Priority 💻, ⭐ goal: addition, level2

#85 Footer Needs Some Improvements #69 Fixed
  public/css/style.css
  public/faviconicon/facebook.png
  public/faviconicon/github.png
  public/faviconicon/instagram.png
  public/faviconicon/linkedin.png
  public/index.html
Labels: good first issue, gssoc23, ⭐ goal: addition, level1

#91 Added footer and navbar in login page
  public/login.html
Labels: gssoc23, ⭐ goal: addition, level2

#95 Added footer and navbar to signup
  public/signup.html
Labels: gssoc23, ⭐ goal: addition, level2

#104 Feature: Divided into Sections of EJS views
  index.js
  package-lock.json
  package.json
  public/css/style.css
  public/index.html
  routes/viewRoutes.js
  views/contactUs.ejs
  views/home.ejs
  views/imagineAi.ejs
  views/includes/footer.ejs
  views/includes/header.ejs
Labels: gssoc23, High Priority 🔥, ⭐ goal: addition, 👨🏻‍🚒 goal: major, level3

#103 Added backend support to generate N images
  controllers/openaiController.js
  routes/openaiRoutes.js
Labels: gssoc23, High Priority 🔥, ⭐ goal: addition, level3

#114 main.js issue #113 fixed
  public/js/main.js
Labels: gssoc23, ⚒️ goal: fix, level1

#112 SignUp Page issue fixed
  public/signup.html
Labels: enhancement, gssoc23, ⚒️ goal: fix, level1

#118 Feature: Login and Sign up integration
  public/css/style.css
  public/login.html
  public/signup.html
  routes/viewRoutes.js
  views/includes/header.ejs
  views/login.ejs
  views/signup.ejs
Labels: enhancement, gssoc23, ⚒️ goal: fix, level2

#121 Contact page need improvement #99 fixed
  public/css/style.css
  views/contactUs.ejs
Labels: enhancement, gssoc23, ⚒️ goal: fix, level2

#127 readme tech stack modify
  readme.md
Labels: documentation, good first issue, gssoc23, level1

#131 changed git clone command
  readme.md
Labels: documentation, gssoc23, level1

#132 Improvement of navbar and home page design #126 Fixed
  public/css/style.css
  views/includes/header.ejs
Labels: gssoc23, Mid Priority 💻, ⚒️ goal: fix, level2

#137 segmentation fixed
  public/css/style.css
  views/home.ejs
Labels: gssoc23, ⚒️ goal: fix, level2

#144 Contact Page Submit Button #142 Fixed
  public/css/style.css
  views/contactUs.ejs
Labels: gssoc23, ⚒️ goal: fix, level2

#136 Responsive NavBar Added
  public/css/style.css
  views/includes/footer.ejs
  views/includes/header.ejs
Labels: gssoc23, Mid Priority 💻, ⚒️ goal: fix, level2

#153 New Responsive Navbar added
  public/css/style.css
  views/includes/header.ejs
Labels: enhancement, gssoc23, ⚒️ goal: fix, level2

#149 Added the examples of image generated through dall-e2
  public/1.png
  public/2.png
  public/3.png
  public/4.png
  public/css/style.css
  views/home.ejs
  views/includes/header.ejs
Labels: gssoc23, ⭐ goal: addition, 👨🏻‍🚒 goal: major, level2

#156 Input tag in Sign in page #150 Fixed
  views/login.ejs
Labels: enhancement, gssoc23, level1

#165 Error on Signup and Login Page
  public/js/main.js
Labels: gssoc23, ⚒️ goal: fix, level2

#166 Issue #75-Make the LOGIN page functional
  .env
  config/db.js
  controllers/authController.js
  index.js
  models/users.js
  package-lock.json
  package.json
  public/css/style.css
  public/css/vanilla-toast.css
  public/js/login.js
  public/js/signup.js
  routes/auth.js
  views/includes/footer.ejs
  views/includes/header.ejs
  views/login.ejs
  views/signup.ejs
Labels: enhancement, gssoc23, High Priority 🔥, 👨🏻‍🚒 goal: major, level3

#180 Made privacypolicy into ejs
  routes/viewRoutes.js
  views/privacypolicy.ejs
Labels: enhancement, gssoc23, level2

#184 CODE_OF_CONDUCT.md File Created
  CODE_OF_CONDUCT.md
Labels: documentation, gssoc23, ⭐ goal: addition, level2

#187 Update in Example Section
  package-lock.json
  public/css/style.css
Labels: enhancement, gssoc23, Mid Priority 💻, ⚒️ goal: fix, level2

#182 [Bug: Fix] Navbar fixed and Redundancy removed
  package-lock.json
  public/css/style.css
  routes/viewRoutes.js
  views/contactUs.ejs
  views/home.ejs
  views/imagineAi.ejs
  views/includes/header.ejs
  views/includes/navbar.ejs
  views/login.ejs
  views/privacypolicy.ejs
  views/signup.ejs
Labels: enhancement, gssoc23, ⚒️ goal: fix, level3

#191 Navbar Responsiveness #185 Fixed
  public/css/style.css
Labels: gssoc23, ⚒️ goal: fix, level2

#198 Added styles to privacy policy
  public/css/style.css
  views/privacypolicy.ejs
Labels: good first issue, gssoc23, level2

#195 Footer added #110
  public/css/style.css
  views/includes/footer.ejs
Labels: gssoc23, High Priority 🔥, ⭐ goal: addition, level3

#205 Footer checked
  public/css/style.css
  views/includes/footer.ejs
Labels: enhancement, gssoc23, ⭐ goal: addition, level3

#215 Pull request template added
  .github/pull_request_template.md
Labels: enhancement, good first issue, gssoc23

#211 Signup and login JS error #210 Issue Fixed
  public/js/login.js
  public/js/signup.js
Labels: bug, gssoc23, ⚒️ goal: fix, level1
