Repository SurajPratap10/Imagine_AI, pull requests merged in 2023-08, with the labels that each got.

#690 Added auto update feature for Copyright year
  views/includes/footer.ejs
Labels: good first issue, gssoc23, level1

#688 feat: revamp documentation issue template 📝✨
  .github/ISSUE_TEMPLATE/Documentation.yml
  .github/ISSUE_TEMPLATE/documentation.yml
Labels: documentation, enhancement, gssoc23, level1

#686 Fixed mistakes in footer
  views/includes/footer.ejs
Labels: good first issue, gssoc23, level1

#687 Created CONTRIBUTING.md for the project keeping in mind readme and codeofconduct.md
  CONTRIBUTING.md
Labels: documentation, enhancement, gssoc23, level2

#648 fix: bad contrast color for link on footer 🛠
  public/css/style.css
Labels: enhancement, gssoc23, level2

#701 improve the UI of the imageDescription section
  public/css/style.css
Labels: enhancement, gssoc23, level1

#697 Clicking on footer logo now redirect to homepage
  views/includes/footer.ejs
Labels: good first issue, gssoc23, level1

#702 improved the privacy policy header that was cutting the navbar
  views/privacypolicy.ejs
Labels: good first issue, gssoc23, ⚒️ goal: fix, level1

#706 improved the ui of contact us page
  package-lock.json
  public/contact.png
  public/css/style.css
  views/contactUs.ejs
Labels: enhancement, gssoc23, Mid Priority 💻, level2

#629 resolve theme & activetab issue
  public/css/style.css
  public/js/main.js
  views/contactUs.ejs
  views/imagineAi.ejs
  views/includes/navbar.ejs
Labels: gssoc23, ⚒️ goal: fix, level3

#610 Responsive About Page
  public/css/style.css
  views/aboutUs.ejs
  views/includes/footer.ejs
  views/includes/header.ejs
  views/includes/navbar.ejs
  views/includes/sidebar.ejs
Labels: enhancement, gssoc23, Mid Priority 💻, level2

#712 Code Refactor of ImagineAi.ejs
  public/css/style.css
  views/imagineAi.ejs
  views/includes/navbar.ejs
Labels: enhancement, gssoc23, level2

#710 Resign the Newsletter component ✨
  views/home.ejs
Labels: enhancement, gssoc23, level2

#717 Add Cors Policy
  index.js
  package-lock.json
  package.json
Labels: enhancement, gssoc23, level2

#725 fix: Added missing alt text in Multiple EJS FILES
  views/home.ejs
  views/imagineAi.ejs
  views/includes/navbar.ejs
Labels: good first issue, gssoc23, level1

#720 updated Contact Us - values of phone no. and email address from home …
  views/contactUs.ejs
Labels: enhancement, good first issue, gssoc23, level1

#737 Added email service to newsletter
  package-lock.json
  views/home.ejs
Labels: enhancement, gssoc23, level3

#726 Fixed Dark Mode Issue {ImagineAI}
  views/imagineAi.ejs
Labels: enhancement, good first issue, gssoc23, level1

#723 Fix: Styling issue in Login.ejs ✨
  views/login.ejs
Labels: enhancement, gssoc23, level1

#741 docs: update guidelines typo and grammar mistakes 📜🖊️
  CONTRIBUTING-GUIDELINES.md
  CONTRIBUTING.md
Labels: documentation, gssoc23, level2

#740 fix: mail form background changing during theme toggle 🔧👷🏻
  public/css/style.css
Labels: gssoc23, ⚒️ goal: fix, level1

#739 feat: revamp newsletter sign up section 🪄✨
  public/css/style.css
  views/home.ejs
Labels: gssoc23, ⚒️ goal: fix, level2

#754 feat: GitHub button Navbar ✨
  views/includes/navbar.ejs
Labels: enhancement, gssoc23, level1

#742 🚀 Enhance Security and Development Experience: Add .env.example, Remove .env, and Provide Vercel Setup Instructions
  .env
  .env.example
  .gitignore
Labels: enhancement, gssoc23, level1

#747 No response on click submit button in contact us page.
  public/js/validation.js
  views/contactUs.ejs
Labels: enhancement, gssoc23, ⚒️ goal: fix, level2

#756 bug is resolved img section is removed
  views/imagineAi.ejs
Labels: bug, gssoc23, level1

#755 chore: update Hero section image ✨
  public/logo.png
  views/home.ejs
Labels: enhancement, gssoc23, level2

#758 refactor: fix wrong repository's credentials on greetings workflow 🔧✅
  .github/workflows/issues.yml
Labels: documentation, good first issue, gssoc23, level1

#761 refactor: bug issue template with enhancements 🪲⚒️✨
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: enhancement, gssoc23, level2

#780 feat: add docs 📃
  CONTRIBUTING-GUIDELINES.md
Labels: enhancement, gssoc23, ⭐ goal: addition, level2

#777 docs: replace tech stack words into attractive badges 📛 ✨
  readme.md
Labels: documentation, good first issue, gssoc23, level1

#783 Added contributors list
  package-lock.json
  routes/viewRoutes.js
  views/includes/navbar.ejs
  views/includes/sidebar.ejs
  views/team.ejs
Labels: enhancement, gssoc23, ⭐ goal: addition, level3

#782 Example Image Download Button
  views/home.ejs
Labels: enhancement, gssoc23, level2

#795 feat: revamp testimonials sliding animation design 🪄✨
  views/includes/sliderr.ejs
Labels: enhancement, gssoc23, level2

#790 Added tutorial video with custom thumbnail
  views/home.ejs
Labels: enhancement, gssoc23, High Priority 🔥, level3

#805 Improved CONTACT US sections contact card
  views/contactUs.ejs
Labels: enhancement, gssoc23, ⚒️ goal: fix, level1

#788 Improving the footer
  views/includes/footer.ejs
Labels: enhancement, gssoc23, level1

#789 feat: revamp contact us form design with enhancements 🪄✨
  views/contactUs.ejs
Labels: enhancement, gssoc23, level2

#814 Provide Smoothness while Scrolling
  public/css/errorStyle.css
Labels: good first issue, gssoc23, level1

#811 refactor: improve pull request template with enhancements 📝🔍
  .github/pull_request_template.md
Labels: enhancement, gssoc23, level2

#606 Added aria attributes to login and signup forms
  views/login.ejs
  views/signup.ejs
Labels: enhancement, gssoc23, level2

#815 Add content and arrange in order.
  readme.md
Labels: documentation, gssoc23, level1

#781 feat: commitlint init ✨
  .husky/commit-msg
  package-lock.json
  package.json
Labels: documentation, gssoc23, level2

#812 The title text as well as other texts in community section changed
  views/team.ejs
Labels: enhancement, gssoc23, level1

#787 feat: revamp hero section image with animated illustration 🪄✨
  package-lock.json
  public/css/style.css
  public/hero.svg
  public/logo.png
  views/home.ejs
Labels: enhancement, gssoc23, level2

#818 feat: Added dynamic contributors section
  readme.md
Labels: enhancement, gssoc23, level1

#822 style: update style of home.ejs and sidebar.ejs
  views/home.ejs
  views/includes/sidebar.ejs
Labels: enhancement, good first issue, gssoc23, level1

#778 refactor: unified workflow for issue locking and greetings 🪄✨
  .github/workflows/issues.yml
  .github/workflows/lock-issue-after-greetings.yml
  .github/workflows/lock-issues.yml
Labels: enhancement, gssoc23, level2

#820 the newsletter get properly aligned(unwanted gap removed)
  public/css/style.css
Labels: enhancement, gssoc23, level1

#830 docs: made gssoc banner adaptive to github light/dark mode 🌞/🌚 ✨
  readme.md
Labels: documentation, enhancement, good first issue, gssoc23, level1

#809 Added a proper table of content to readme + added cool emojis
  readme.md
Labels: documentation, good first issue, gssoc23, level1

#824 Start Main Functionality of DALL-E Image Generator - CORS Fix and Image Container
  .env
  index.js
  package.json
  views/imagineAi.ejs
Labels: gssoc23, High Priority 🔥, ⚒️ goal: fix, 👨🏻‍🚒 goal: major, level3

#835 one unwanted segment area removed
  views/home.ejs
Labels: good first issue, gssoc23, ⚒️ goal: fix, level1

#834 changing hover for back to top button
  views/includes/topToBottomScrollButton.ejs
Labels: good first issue, gssoc23, level1

#837 Added 3d Animations to Contributors
  views/team.ejs
Labels: enhancement, gssoc23, level2

#838 feat: brand new mockup for Imagine AI 🚀🔥
  public/banner.webp
  readme.md
Labels: enhancement, gssoc23, level2

#843 Fix Table of Contents
  readme.md
Labels: good first issue, gssoc23, level1

#845 🚀 Added 3D Swiper Animation with Beautiful Colors for Testimonial Section
  public/css/silder.css
  public/css/style.css
  public/images/1000_F_218572097_iwqkZBplW7t68TDmwyf9yurde2CddXnB.jpg
  public/images/on.png
  public/images/team10.jpg
  public/images/team10.jpg.png
  public/images/team8.jpg
  public/images/team8.jpg.png
  public/images/team9.jpg
  public/images/team9.jpg.png
  public/js/slider.js
  routes/viewRoutes.js
  views/aboutUs.ejs
  views/includes/header.ejs
  views/includes/sliderr.ejs
  views/slider.ejs
Labels: enhancement, gssoc23, level3
