Repository SurajPratap10/Imagine_AI, pull requests merged in 2023-06, with the labels that each got.

#220 [Fixed]: Removed bootstrap clashes with navbar class
  views/home.ejs
Labels: bug, gssoc23, ⚒️ goal: fix, level2

#229 Fixing the textarea font to sans-serif
  public/css/style.css
Labels: enhancement, good first issue, gssoc23, level1

#230 fixes contact page bug
  public/js/signup.js
Labels: bug, gssoc23, ⚒️ goal: fix, level2

#232 Fix : validate openAI key and detailed warnings
  controllers/openaiController.js
  public/css/style.css
  public/js/main.js
Labels: enhancement, gssoc23, ⚒️ goal: fix, level3

#235 preloader added
  package-lock.json
  public/css/style.css
  public/js/main.js
  views/contactUs.ejs
  views/home.ejs
  views/imagineAi.ejs
  views/includes/PRE.ejs
  views/login.ejs
  views/privacypolicy.ejs
  views/signup.ejs
Labels: enhancement, gssoc23, ⭐ goal: addition, level3

#248 Issue with contact us Page #239
  public/css/style.css
Labels: gssoc23, Mid Priority 💻, ⚒️ goal: fix, level2

#252 footer added
  package-lock.json
  package.json
  views/includes/footer.ejs
Labels: enhancement, gssoc23, ⭐ goal: addition, level3

#256 Add Back to Homepage button on 404 page
  public/css/errorStyle.css
  public/error.html
Labels: gssoc23, ⭐ goal: addition, level2

#261 Home Section Improvement #260 Resolved
  public/css/style.css
  public/logo-no-background.png
  views/home.ejs
  views/includes/footer.ejs
Labels: enhancement, gssoc23, Mid Priority 💻, level2

#268 Made footer dark
  public/css/style.css
  views/includes/footer.ejs
Labels: enhancement, gssoc23

#284 Changed to webp
  cover.png
  cover.webp
  public/1.webp
  public/2.webp
  public/3.webp
  public/4.webp
  public/css/w8.png
  public/css/w8.webp
  public/favicon.webp
  public/faviconicon/erroricon.png
  public/faviconicon/erroricon.webp
  public/faviconicon/facebook.png
  public/faviconicon/facebook.webp
  public/faviconicon/github.png
  public/faviconicon/github.webp
  public/faviconicon/instagram.png
  public/faviconicon/instagram.webp
  public/faviconicon/linkedin.png
  public/faviconicon/linkedin.webp
  public/logo-no-background.png
  public/logo-no-background.webp
  views/home.ejs
  views/imagineAi.ejs
  views/includes/footer.ejs
Labels: enhancement, gssoc23, level2

#283 Oauth added
  .env
  controllers/googleAuthContoller.js
  index.js
  package-lock.json
  package.json
  views/login.ejs
  views/signup.ejs
Labels: enhancement, gssoc23, ⭐ goal: addition, level3

#301 added hover effect on navbar + better fonts
  public/css/style.css
  views/includes/navbar.ejs
Labels: good first issue, gssoc23, level1

#298 feat: Sticky navbar added
  public/css/style.css
Labels: enhancement, gssoc23, level1

#294 Email validation added
  views/includes/footer.ejs
Labels: good first issue, gssoc23, level1

#304 Meta tags added
  views/includes/header.ejs
Labels: good first issue, gssoc23, level1

#305 Alt attributes added
  views/home.ejs
  views/imagineAi.ejs
Labels: good first issue, gssoc23, level1

#317 Update readme.md
  readme.md
Labels: documentation, gssoc23, level1

#310 Solve the responsive issue within popup card Popup Text is overflowing …
  public/css/style.css
  views/imagineAi.ejs
Labels: gssoc23, ⚒️ goal: fix, level2

#295 Contact Us form validation added
  views/contactUs.ejs
Labels: enhancement, good first issue, gssoc23, level1

#329 Improved home page, socials, about us page, dark mode button and refactored CSS
  public/css/style.css
  views/aboutUs.ejs
  views/contactUs.ejs
  views/home.ejs
  views/includes/footer.ejs
  views/includes/header.ejs
  views/includes/navbar.ejs
Labels: gssoc23, Mid Priority 💻, ⚒️ goal: fix, level3

#339 Adding FAQ Section
  public/css/style.css
  views/imagineAi.ejs
Labels: enhancement, gssoc23, level2

#336 Typo error solved
  views/aboutUs.ejs
Labels: good first issue, gssoc23, level1

#335 [Add]: Icons/Buttons for OAuth (sign in/ sign up)
  public/css/style.css
  views/login.ejs
  views/signup.ejs
Labels: enhancement, gssoc23, level2

#334 dependabot.yml file added
  .github/dependabot.yml
Labels: enhancement, gssoc23, level2

#355 Enhanced the Design of Contact Us Page
  public/contactus.png
  public/css/style.css
  views/contactUs.ejs
Labels: gssoc23, level2

#267 Updated the Footer input text ui and updated new css according to the…
  views/includes/footer.ejs
Labels: enhancement, gssoc23, level1

#375 Aman singh6574 issue#359
  readme.md
Labels: documentation, enhancement, good first issue, gssoc23, level1

#369 changes-in-navbar
  public/css/style.css
  views/includes/navbar.ejs
Labels: enhancement, gssoc23, level2

#380 Added the CodeQL workflow
  .github/workflows/codeql.yml
Labels: enhancement, gssoc23, level2

#366 Fix color of elements of "Subscribe Us" section.
  views/includes/footer.ejs
Labels: good first issue, gssoc23, ⚒️ goal: fix, level1

#367 Fix the enter email bug #362
  public/css/style.css
Labels: good first issue, gssoc23, ⚒️ goal: fix, level1

#382 fixes path in navbar
  views/includes/navbar.ejs
Labels: enhancement, gssoc23, ⚒️ goal: fix, level1

#397 Contact us page modified
  public/css/style.css
  views/contactUs.ejs
Labels: enhancement, gssoc23, level2

#374 Improved lighthouse score
  public/banner.png
  public/banner.webp
  public/brian1.png
  public/brian1.webp
  public/chloe1.png
  public/chloe1.webp
  public/chris1.png
  public/chris1.webp
  public/conditioning1.png
  public/conditioning1.webp
  public/contactus.png
  public/contactus.webp
  public/error.html
  public/generation.png
  public/generation.webp
  public/js/signup.js
  public/modal.png
  public/modal.webp
  public/sarah2.png
  public/sarah2.webp
  public/style.png
  public/style.webp
  views/aboutUs.ejs
  views/contactUs.ejs
  views/home.ejs
  views/imagineAi.ejs
  views/includes/footer.ejs
  views/includes/header.ejs
  views/login.ejs
  views/signup.ejs
Labels: enhancement, gssoc23

#418 Added code for Icon alignment
  public/css/style.css
Labels: good first issue, gssoc23, ⚒️ goal: fix, level1

#318 💡 [FEAT]: ACCESSIBLE SOCIAL ANCHORS W/ A11Y PRINCIPLES
  public/css/style.css
  views/includes/footer.ejs
Labels: enhancement, gssoc23, level2

#421 Critical SEO Tag Implementation Issues: missing tags which effect Search Engine Visibility and Performance #297
  views/includes/footer.ejs
  views/includes/header.ejs
Labels: enhancement, gssoc23, ⭐ goal: addition, level2

#354 Solving Google Login issue
  models/users.js
Labels: enhancement, gssoc23, level2

#458 Redesigning the 404 Page for Improved User Experience, current page UI lags
  public/error.html
Labels: enhancement, gssoc23, Mid Priority 💻, level3

#425 changes-made-home-page
  public/css/style.css
  views/aboutUs.ejs
Labels: enhancement, good first issue, gssoc23, level1

#446 Imagine-AI Image Description aligned properly
  views/imagineAi.ejs
Labels: enhancement, gssoc23, ⚒️ goal: fix, level2

#442 Changed Position of Dark/Light Toggle Button
  views/includes/navbar.ejs
Labels: enhancement, gssoc23, level2

#447 Added SideBar for Small device with hamburger icon
  views/aboutUs.ejs
  views/contactUs.ejs
  views/home.ejs
  views/imagineAi.ejs
  views/includes/sidebar.ejs
  views/login.ejs
  views/privacypolicy.ejs
  views/signup.ejs
Labels: enhancement, gssoc23, ⭐ goal: addition, level3

#414 Input redesign
  public/css/style.css
  views/login.ejs
Labels: enhancement, gssoc23, level2

#475 fix: sign in page
  package-lock.json
  views/login.ejs
Labels: enhancement, gssoc23, ⚒️ goal: fix, level1

#468 Added robots.txt file
  robots.txt
Labels: enhancement, gssoc23, level1

#463 Added sitemap.xml
  public/sitemap.xml
Labels: enhancement, gssoc23

#386 Fixes Navbar
  public/css/style.css
  public/js/main.js
  views/includes/navbar.ejs
Labels: gssoc23, Mid Priority 💻, ⚒️ goal: fix, level3

#488 improved contact page - #452 PR conflits resolved
  public/css/style.css
  views/contactUs.ejs
  views/includes/footer.ejs
Labels: enhancement, gssoc23, level2

#489 navbar-enhanced
  views/home.ejs
  views/includes/navbar.ejs
Labels: help wanted, gssoc23, High Priority 🔥, ⚒️ goal: fix, level3

#462 [ADD]: OPEN GRAPH & TWITTER META ELEMENTS ✨
  views/includes/header.ejs
Labels: documentation, enhancement, good first issue, gssoc23, level1

#472 Added responsive for login and signup pages
  public/css/style.css
  views/login.ejs
Labels: gssoc23, ⚒️ goal: fix, level2

#494 make Contact us section Functional: Interactive Phone Number and Email Integration
  views/includes/footer.ejs
Labels: enhancement, gssoc23, level3

#497 Added New Logo for the website
  public/css/style.css
  public/imagine-ai-low-resolution-logo-color-on-transparent-background.png
  views/home.ejs
  views/includes/footer.ejs
  views/includes/navbar.ejs
Labels: enhancement, gssoc23, level2

#503 redesigned signup page
  views/signup.ejs
Labels: enhancement, gssoc23, ⚒️ goal: fix, level1

#505 🛠️ [FIX]: IMPROPER ALIGNMENT & REMOVED INLINE STYLES FOR COPYRIGHT TEXT
  views/includes/footer.ejs
Labels: enhancement, good first issue, gssoc23, level1

#502 contact-validation
  public/css/style.css
  public/js/validation.js
  views/contactUs.ejs
Labels: enhancement, gssoc23, level2

#504 Show password icon
  views/includes/header.ejs
  views/login.ejs
  views/signup.ejs
Labels: enhancement, good first issue, gssoc23, level2

#509 Improve the FAQ Section
  public/css/style.css
Labels: enhancement, gssoc23, level2
