Repository SurajPratap10/Imagine_AI, pull requests merged in 2023-07, with the labels that each got.

#526 feat : Added voice assistant for DALLE prompts and FAQ about website
  .env
  views/alan.ejs
  views/imagineAi.ejs
Labels: enhancement, gssoc23, High Priority 🔥, ⭐ goal: addition, level3

#523 style: improve loader animation
  public/css/style.css
  public/js/main.js
  views/includes/PRE.ejs
Labels: enhancement, gssoc23, level2

#520 Newsletter section modified
  public/css/style.css
  views/home.ejs
Labels: enhancement, good first issue, gssoc23, level1

#522 fix(navbar): fixing navbar style and functionality
  public/css/style.css
  views/aboutUs.ejs
  views/contactUs.ejs
  views/home.ejs
  views/includes/navbar.ejs
Labels: enhancement, gssoc23, level2

#524 Added lazy loading to img tags
  public/error.html
  views/aboutUs.ejs
  views/contactUs.ejs
  views/home.ejs
  views/imagineAi.ejs
  views/includes/footer.ejs
  views/includes/navbar.ejs
Labels: enhancement, gssoc23, level1

#534 Adding Sharing Button and Fixing Image Positioning
  public/css/style.css
  public/js/main.js
  views/imagineAi.ejs
Labels: enhancement, gssoc23, High Priority 🔥, ⭐ goal: addition, level3

#529 changed to the icons
  views/includes/footer.ejs
Labels: enhancement, good first issue, gssoc23, level1

#540 IMAGINE-AI section enhanced
  package-lock.json
  package.json
  public/css/style.css
Labels: enhancement, gssoc23, level2

#546 Added Functionality that users to generate multiple images in Imagine AI DALL·E website
  controllers/openaiController.js
  public/css/style.css
  public/js/main.js
  routes/openaiRoutes.js
Labels: enhancement, gssoc23, High Priority 🔥, level3

#550 Hover effect added on the footer element
  public/css/style.css
  views/includes/footer.ejs
Labels: enhancement, gssoc23, level1

#551 feat: create workflow ⚡
  .github/workflows/lock.yml
Labels: gssoc23, ⭐ goal: addition, level2

#562 Captcha
  public/css/style.css
  public/js/signup.js
  views/login.ejs
  views/signup.ejs
Labels: gssoc23, High Priority 🔥, ⭐ goal: addition, level3

#565 feat: add workflow script for prevent multiple issues 🔐
  .github/workflows/prevent_multiple_issues.yml
Labels: gssoc23, ⭐ goal: addition, level2

#559 fix: image disortion for logo image 🛠
  public/css/style.css
Labels: good first issue, gssoc23, level1

#572 🔔💫 Enhance Webpage View with Toast Notifications instead of Default Alerts
  public/css/toastr.min.css
  public/css/vanilla-toast.css
  public/js/toastr.min.js
  public/js/validation.js
  views/includes/footer.ejs
  views/includes/header.ejs
Labels: enhancement, gssoc23, High Priority 🔥, ⭐ goal: addition, level3

#571 Updating add hamburger menu to contact-us page
  public/css/style.css
  views/contactUs.ejs
Labels: enhancement, gssoc23, Mid Priority 💻, ⚒️ goal: fix, level2

#569 style added on scrollbar
  public/css/style.css
Labels: enhancement, good first issue, gssoc23, level1

#579 Added Licenses section and badge in readme
  readme.md
Labels: documentation, good first issue, gssoc23, level1

#585 login page issue were resolved
  public/css/style.css
  views/login.ejs
Labels: enhancement, gssoc23, level2

#598 [GSSoC'23] Fonts added for the header
  views/home.ejs
Labels: enhancement, gssoc23, level2

#597 [GSSoC'23] Styling Back to Top Arrow Button
  views/includes/topToBottomScrollButton.ejs
Labels: enhancement, gssoc23, level2

#608 Added favicon to the website
  views/includes/header.ejs
Labels: enhancement, gssoc23, level1

#607 Added gap between forms and footer
  public/css/style.css
  views/signup.ejs
Labels: gssoc23, ⚒️ goal: fix, level1

#599 copyright improvement
  views/includes/footer.ejs
Labels: good first issue, gssoc23, level1

#600 home logo navigation added
  views/includes/navbar.ejs
Labels: enhancement, good first issue, gssoc23, level1

#604 Two changes in this code al line 40 to 44 and 66 to 87
  index.js
Labels: enhancement, gssoc23, level2

#614 margin added
  views/imagineAi.ejs
Labels: good first issue, gssoc23, ⚒️ goal: fix, level1

#595 Adjusted the height of the login and signup page
  public/css/style.css
  views/login.ejs
  views/signup.ejs
Labels: good first issue, gssoc23, level1

#566 Create issues.yml
  .github/workflows/issues.yml
Labels: good first issue, gssoc23, level1

#613 Update readme.md and Deployment Link
  readme.md
Labels: good first issue, gssoc23, level1

#619 Improved the UI of the scroll to top button
  views/includes/topToBottomScrollButton.ejs
Labels: gssoc23, ⚒️ goal: fix, level1

#618 Fixed Callback URL Issue
  .env
  index.js
  views/imagineAi.ejs
Labels: gssoc23, ⚒️ goal: fix, level2

#634 added underline effects over hover effect
  public/css/style.css
  views/includes/navbar.ejs
Labels: enhancement, good first issue, gssoc23, level1

#649 Fixed responsiveness newsletter.css
  public/css/fixed responsiveness newsletter.css
Labels: gssoc23, ⚒️ goal: fix, level2

#659 Fixed Generate image stuck on loading error: URGENT 🚨
  public/js/main.js
  views/imagineAi.ejs
  views/includes/header.ejs
Labels: gssoc23, High Priority 🔥, ⚒️ goal: fix

#670 fix: missing mobile sidebar on form page 🛠
  views/imagineAi.ejs
Labels: good first issue, gssoc23, ⚒️ goal: fix, level1

#663 fixed alignment of privacy policy page + made code organized
  views/login.ejs
  views/privacypolicy.ejs
Labels: enhancement, gssoc23, level2

#651 Implemented exception handling in login logic.
  controllers/authController.js
Labels: enhancement, gssoc23, level1

#658 Navabar in imagineAI page
  views/imagineAi.ejs
  views/includes/sidebar.ejs
Labels: enhancement, gssoc23, Mid Priority 💻, level2

#684 added link to the logo in footer and navabr
  views/includes/footer.ejs
Labels: good first issue, gssoc23, level1

#675 removed mistakes and misspells form code_of_conduct (en-uk)
  CODE_OF_CONDUCT.md
Labels: documentation, enhancement, good first issue, gssoc23, ⚒️ goal: fix, level1
