Repository SurajPratap10/Imagine_AI, pull requests merged in 2024-10, with the labels that each got.

#1116 Fix Hamberger Menu Z-Index Issue and Mobile Overflow Scroll Due to Iframe Width
  views/home.ejs
  views/includes/sidebar.ejs
Labels: ⚒️ goal: fix, level1, gssoc-ext, hacktoberfest-accepted

#1124 Fix Iframe Width and Newsletter Validation & Input Visibility
  views/home.ejs
Labels: enhancement, ⚒️ goal: fix, level1, gssoc-ext, hacktoberfest-accepted

#1129 Fix: Sidebar Collapse via Hamburger Menu on Smaller Screens
  views/includes/sidebar.ejs
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1132 Improved the contact us details section
  .husky/commit-msg
  package-lock.json
  package.json
  views/contactUs.ejs
Labels: enhancement, level2, gssoc-ext, hacktoberfest-accepted

#1135 Fix: Adjust Social Media Icon Size on Login Page for All Screen Sizes
  views/login.ejs
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1142 feat: Add hover effects for improved interactivity #1118
  public/css/style.css
Labels: good first issue, level1, gssoc-ext, hacktoberfest-accepted

#1159 corrected email in footer of contactUs page
  views/contactUs.ejs
Labels: ⚒️ goal: fix, level2, gssoc-ext, hacktoberfest-accepted

#1167 Social Media login fixed
  views/login.ejs
Labels: ⚒️ goal: fix, level1, gssoc-ext, hacktoberfest-accepted

#1171 Change in contactus and login page
  package-lock.json
  views/contactUs.ejs
  views/login.ejs
Labels: ⚒️ goal: fix, level2, gssoc-ext, hacktoberfest-accepted

#1169 [style]: Hamburger overflow even after click and close button not working
  views/includes/sidebar.ejs
Labels: ⚒️ goal: fix, level1, gssoc-ext, hacktoberfest-accepted

#1175 Fix Community Page Responsiveness and Enhance Design
  views/team.ejs
Labels: ⚒️ goal: fix, level2, gssoc-ext, hacktoberfest-accepted

#1177 [UI ENHANCEMENT] : Added gsap animatin to homepage & navbar
  package-lock.json
  package.json
  views/home.ejs
  views/includes/header.ejs
  views/includes/navbar.ejs
Labels: level3, gssoc-ext, hacktoberfest-accepted

#1183 Fix Navbar Size and Enhance Page Design
  views/team.ejs
Labels: good first issue, level1, gssoc-ext, hacktoberfest-accepted

#1182 Fixees the width of the testimonial section
  views/aboutUs.ejs
  views/slider.ejs
Labels: good first issue, level1, gssoc-ext, hacktoberfest-accepted

#1187 Fixed: Added Scroll-to-Top button on the Community page for better na…
  views/team.ejs
Labels: good first issue, level1, gssoc-ext, hacktoberfest-accepted

#1195 Bug Fixed: Updated light/dark theme toggle functionality for Sign In/…
  views/aboutUs.ejs
  views/home.ejs
  views/includes/navbar.ejs
  views/login.ejs
  views/signup.ejs
Labels: bug, level2, gssoc-ext, hacktoberfest-accepted

#1202 issue#1197 solved , chatbot added
  package-lock.json
  views/aboutUs.ejs
  views/contactUs.ejs
  views/home.ejs
  views/imagineAi.ejs
  views/login.ejs
  views/privacypolicy.ejs
  views/signup.ejs
  views/slider.ejs
  views/team.ejs
Labels: ⭐ goal: addition, level3, gssoc-ext, hacktoberfest-accepted

#1211 Signin Signup ui fixed
  package-lock.json
  package.json
  public/css/style.css
  views/login.ejs
  views/signup.ejs
Labels: ⚒️ goal: fix, level3, gssoc-ext, hacktoberfest-accepted

#1214 Add Hover Effects and Glow to Heading and Image
  public/css/style.css
Labels: good first issue, level1, gssoc-ext, hacktoberfest-accepted

#1215 Add Hover Effects for Input and Button Fields in Newsletter Section
  views/home.ejs
Labels: good first issue, level1, gssoc-ext, hacktoberfest-accepted

#1213 Fixes the Border radius Issues and Newsletter Alignment
  public/css/silder.css
  public/css/style.css
  views/home.ejs
Labels: ⚒️ goal: fix, level1, gssoc-ext, hacktoberfest-accepted

#1231 ✨the navbar has been added ✨
  .env
  views/aboutUs.ejs
  views/contactUs.ejs
Labels: level3, gssoc-ext, hacktoberfest-accepted

#1235 Remove unnecessary .di h1 styles causing UI bottom bar issues
  public/css/style.css
Labels: bug, level2, gssoc-ext, hacktoberfest-accepted

#1216 #1162 solved : aboutUs page updated
  package-lock.json
  views/aboutUs.ejs
  views/includes/feature.ejs
  views/includes/footer2.ejs
  views/includes/navbar.ejs
Labels: level3, gssoc-ext, hacktoberfest-accepted

#1233 #1206 [style]: i would like to add an intro
  index.js
  public/videos/intro.mp4
  routes/viewRoutes.js
  views/intro.ejs
Labels: level2, gssoc-ext, hacktoberfest-accepted

#1241 Fixed overlapping of arrow and chatbot icon
  views/includes/topToBottomScrollButton.ejs
Labels: level2, gssoc-ext, hacktoberfest-accepted

#1251 Main
  public/css/style.css
Labels: level2, gssoc-ext, hacktoberfest-accepted

#1248 Fix Overflow and Overlap Issue on Contact Us Page
  views/contactUs.ejs
Labels: ⚒️ goal: fix, level1, gssoc-ext, hacktoberfest-accepted

#1254 recovery-password-feature
  package-lock.json
  package.json
  routes/viewRoutes.js
  views/forgot-password.ejs
  views/login.ejs
Labels: ⭐ goal: addition, level2, gssoc-ext, hacktoberfest-accepted

#1252 Added expand button for sample images
  views/home.ejs
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1253 Some Changes in text.ejs file
  views/team.ejs
Labels: good first issue, level1, gssoc-ext, hacktoberfest-accepted

#1249 Activated Dark theme in community page and also the text
  views/includes/navbar.ejs
  views/team.ejs
Labels: level2, gssoc-ext, hacktoberfest-accepted

#1260 added feedback feature
  .env
  controllers/feedbackController.js
  index.js
  package-lock.json
  package.json
  routes/feedback.js
  routes/viewRoutes.js
  views/feedback.ejs
  views/includes/navbar.ejs
Labels: High Priority 🔥, level3, gssoc-ext, hacktoberfest-accepted

#1246 Fix Responsiveness Issues and Overlap of Hamburger Menu and Dark Mode Toggle
  public/css/style.css
  views/includes/sidebar.ejs
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1281 Subscribe section bottom line closer to input field
  views/includes/footer.ejs
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1286 Adding Footer in Feedback page
  package-lock.json
  views/feedback.ejs
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1293 ✨contributor page has been added✨
  contributor/contributor.css
  contributor/contributor.html
  contributor/contributor.js
  index.js
  views/includes/footer.ejs
Labels: ⭐ goal: addition, level3, gssoc-ext, hacktoberfest-accepted

#1283 Implement GitHub PR Issue Checker Workflow
  .github/workflows/pr-checker.yaml
Labels: level2, gssoc-ext, hacktoberfest-accepted

#1297 add_nav_in_contact_page_in_mobile_view
  views/contactUs.ejs
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1284 Enhance the text-visibility of Contact Us, About Us Page.
  public/css/style.css
Labels: good first issue, level1, gssoc-ext, hacktoberfest-accepted

#1304 Github actions for more connectivity!
  .github/workflows/issue_open_close.yml
  .github/workflows/pr_merged.yaml
  .github/workflows/pr_raise.yml
Labels: ⭐ goal: addition, level2, gssoc-ext, hacktoberfest-accepted

#1307 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, good first issue, level1, gssoc-ext, hacktoberfest-accepted

#1317 Text left aligned
  package-lock.json
  public/css/style.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1308 Add Chatbot Functionality to IMAGINE - AI
  views/aboutUs.ejs
  views/contactUs.ejs
  views/home.ejs
  views/imagineAi.ejs
  views/privacypolicy.ejs
  views/signup.ejs
  views/slider.ejs
  views/team.ejs
Labels: level2, gssoc-ext, hacktoberfest-accepted

#1338 IMAGINE AI Update db.js
  config/db.js
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1355 fixed text overlapping in language translator
  package-lock.json
  views/aboutUs.ejs
  views/alan.ejs
  views/contactUs.ejs
  views/feedback.ejs
  views/forgot-password.ejs
  views/home.ejs
  views/imagineAi.ejs
  views/intro.ejs
  views/login.ejs
  views/privacypolicy.ejs
  views/signup.ejs
  views/slider.ejs
  views/team.ejs
Labels: level3, gssoc-ext, hacktoberfest-accepted
